title = "Universal"
baseURL = "https://www.somicre.com/"
theme = "hugo-universal-theme"
#url = "https://Osousa8.github.io"
#themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]
#Non-Dropdown Menu Item

[[menu.main]]
    identifier = "homePage"
    name       = "Home"
    url        = "/"
    weight     = -1


# Dropdown Title
[[menu.main]]
    name       = "Produtos"
    identifier = "menu.home"
    url        = "/vida-feliz"
    weight     = 1
#Dropdown Content
[[menu.main]]
    name       = "Vida Feliz"
    url        = "/productos/vida-feliz"
    weight     = 1
    parent     = "menu.home"

[[menu.main]]
    name       = "Crédito Informática"
    url        = "/productos/credito-informatica"
    weight     = 2
    parent     = "menu.home"

[[menu.main]]
    name       = "Crédito Pessoal"
    url        = "/productos/credito-pessoal"
    weight     = 3
    parent     = "menu.home"

[[menu.main]]
    name       = "Crédito Saúde"
    url        = "/productos/credito-saude"
    weight     = 4
    parent     = "menu.home"

[[menu.main]]
    name       = "Microcrédito"
    url        = "/productos/microcredito"
    weight     = 5
    parent     = "menu.home"
#Dropdown Content End

#Non-Dropdown Menu Item

[[menu.main]]
    name       = "Parceiros"
    identifier = "section.ap-about"
    url        = "/parceiros"
    weight     = 2

[[menu.main]]
    name       = "Noticias Somicre"
    identifier = "section.ap-marketing"
    url        = "/noticias-somicre"
    weight     = 3

[[menu.main]]
    identifier = "contact"
    name       = "Contactos"
    url        = "/contactos/contact/"
    weight     = 7


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+244 222 020 276"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:geral@somicre.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"
    
[[menu.topbar]]
    weight = 3
    name = "Fax"
    url = "fax:+244 220 012 315"
    pre = "<i class='fas fa-2x fa-printer'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = ""
    comments = false

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"
    copyright = "<p>SOMICRE, SA | Edificio Talatona Residence Plaza, Loja G - Centralidade Talatona, Luanda - Angola Copyright 2012, Somicre. Todos os direitos reservados.</p>"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Somicre"

    logo = "/SomicreLogo.png"
    logo_small = "/smolicon.png"
    favicon = "/Favicon.png"
    contact_url = "/contactos/contact/"
    address = """<p>Tel: +244 222 020 276<br>
                Fax: +244 220 012 315<br>
                Email: geral@somicre.com</p>"""

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +244 222 020 276 or geral@somicre.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+244 222 020 276" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
